### ISSUE TITLE
Error when compiling on 32-bit machine

### ISSUE THREAD

**Issue by maaaks** [dymk/temple#22]
My friend with a 32-bit Ubuntu can't compile Temple without manually modifying sources:

> ../../../.dub/packages/temple-master/src/temple/func_string_gen.d(237): Error: cannot implicitly convert expression ((*cDelimPos)._expand_field_0) of type ulong to uint
../../../.dub/packages/temple-master/src/temple/func_string_gen.d(302): Error: function temple.util.munchHeadOf (ref string a, ref string b, uint amt) is not callable using argument types (string, string, ulong)
../../../.dub/packages/temple-master/src/temple/func_string_gen.d(312): Error: cannot implicitly convert expression (delim_pos) of type immutable(ulong) to uint
../../../.dub/packages/temple-master/src/temple/func_string_gen.d(313): Error: function temple.util.munchHeadOf (ref string a, ref string b, uint amt) is not callable using argument types (string, string, immutable(ulong))
../../../.dub/packages/temple-master/src/temple/temple.d(60):        called from here: __temple_gen_temple_func_string("", "", "")
TempleFunc(68): Error: argument to mixin must be a string, not (__TempleFuncStr) of type const(immutable(char)[])
src/temple/temple.d(75): Error: undefined identifier TempleFunc
src/temple/temple.d(169): Error: template instance temple.temple.Temple!("", "", void) error instantiating
Compiling Temple with Vibed support
FAIL ../../../.dub/packages/temple-master/.dub/build/-debug-linux.posix-x86-dmd_2066-6394FE5D72CAB3DB200BBDB968FC3BD4/ temple staticLibrary
Error executing command build: dmd failed with exit code 1.
```

**Comment by dymk** [comment]
@maaaks, is this still an issue?

**Comment by maaaks** [comment]
No, everything seems to build correctly now.
