### ISSUE TITLE
Error when compiling with DMD 2.068.1-b2

### ISSUE THREAD

**Issue by BBasile** [dymk/temple#31]
I compile temple with the latest beta and get:

>
C:\Dev\dmd2\windows\bin\..\..\src\phobos\std\variant.d: Error: function std.variant.VariantN!20u.VariantN.__xopEquals errors compiling the function

I compile without defining the version identifier that enable vibe.d.
This is important because it may be a Phobos regression and the release will come fast.

**Comment by dymk** [comment]
I'm testing with `DMD v2.068.1-b2` on OSX and I'm unable to reproduce (unittests compile and run without error). Perhaps try removing your `dub.selections.json`, and run with `dub --force` to force a clean build?

**Comment by BBasile** [comment]
I'm compiling with Coedit & dmd 32 bit under win32. temple is part of a "meta" project group:

https://github.com/BBasile/metad/blob/master/projects/temple.coedit

The unittests also compiles and pass with (second config) but the static library files doesn't not.
What's passed to DMD is basically this command line:

>
dmd \src\temple\delims.d \src\temple\func_string_gen.d  \src\temple\output_stream.d \src\temple\temple_context.d \src\temple\util.d \src\temple\vibe.d \src\temple\package.d -w -lib -O -release -of..\libs\temple

When you build with dub it's by default in debug mode. Try with dmd **-release** switch, you'll see what I'm talking about.

**Comment by BBasile** [comment]
to be more clear:

compiles with

> dub build --build=release

**Comment by dymk** [comment]
This does seem to be a phobos regression: 

Reduced test case: 
```
import std.variant ;
class TempleContext
{
  // context variables
  Variant[string] vars;

  ref var(string name)
  {
      vars[name] = Variant();
  }
}
```

**Comment by BBasile** [comment]
Should I file a Bugzilla  report or will you do ?

**Comment by dymk** [comment]
https://issues.dlang.org/show_bug.cgi?id=15017

**Comment by dymk** [comment]
This actually looks like a DMD regression, not a Phobos one
