### ISSUE TITLE
Proper usage with vibe.d's web interface

### ISSUE THREAD

**Issue by whitebyte** [dymk/temple#35]
Hi,
there is an example of vibe.d integration in the docs, but it uses "raw" low-levev rounting, where every route handler takes HTTPServerRequest and HTTPServerResponse as parameters:

``` d
void handleRequest(HTTPServerRequest req, HTTPServerResponse res) {
    if (req.path == "/")
        res.writeBody("Hello, World!", "text/plain");
}
```

...semething like this.

Vibe.d also offers [WebFramework feature](http://vibed.org/docs#web), which doesn't use HTTPServerRequest and HTTPServerResponse explicitly. Typical route handler in this case looks like this:

``` d
void index() {
    bool authenticated = ms_authenticated;
    render!("index.dt", authenticated);
}
```

Since Temple's `renderTempleFile` and frieds requires HTTPServerResponse-type parameter, it's not clear to me how to use it with WebFramework. Right now I'm doing it this way:

``` d
void index(HTTPServerResponse res) {
    auto context = new TempleContext;
    context.pagetitle = "Test";
    renderTempleFile!("index.html.emd")(res, context);
}
```

It works, but I hope there is more elegant way.

**Comment by DarkRiDDeR** [comment]
Hi, how else can send the functions space of HTTPServerResponse for rendering? I think that your last example is the most minimalistic.

**Comment by whitebyte** [comment]
Well, Diet template can work without parameters at all when used from WebFramework class (see 2nd code example from my message). I want to know how to archeve the same effect with Temple.

**Comment by DarkRiDDeR** [comment]
I think that this possibility is not yet implemented in Temple.

**Comment by whitebyte** [comment]
...
ping @dymk

**Comment by dymk** [comment]
Hi, sorry about that, Temple has sorta flown under my radar. 

I'll take a look into how vibe's diet `render!()` function is being called within a web interface, and how it's *somehow* getting a reference to the HTTP request/response objects when the web interface isn't inheriting from any superclasses. It's not entirely clear vibe how is accomplishing that when calling `registerWebInterface(SomeClass)`

**Comment by dymk** [comment]
In theory, this is actually pretty easy, looking through vibe. The task handling the current http request has a task local request context. However, it's private and internal to the module `vibe.web.web`, which implements render/redirect/etc for web interfaces: https://github.com/rejectedsoftware/vibe.d/blob/92df36b68560fae6697cc9c35a868ae2a52d6a93/source/vibe/web/web.d#L579

There's not much I can do to support this, aside from proposing to @s-ludwig to have public methods exposed for getting handles to the current task's `HTTPServerRequest` and `HTTPServerResponse`.
