### ISSUE TITLE
Vibe.d support broken for vibe.d 0.2.78

### ISSUE THREAD

**Issue by kingsleyh** [dymk/temple#37]
Compiling Temple with Vibed support
../../../.dub/packages/temple-0.7.4/src/temple/vibe.d(90,15): Error: expression req.params of type DictionaryList!(string, true, 8LU, false) does not have a boolean value

looks like this pull request will fix it: https://github.com/dymk/temple/pull/36

Please could you take the pull request and apply it.

**Comment by dymk** [comment]
Closed with #36
